/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_api_stories_get"];
        put?: never;
        /** Create Story Route */
        post: operations["create_story_route_api_stories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Route */
        get: operations["get_story_route_api_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_stories__story_id__turns_get"];
        put?: never;
        /** Submit Turn */
        post: operations["submit_turn_api_stories__story_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/visible-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visible State */
        get: operations["get_visible_state_api_stories__story_id__visible_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setup State */
        get: operations["get_setup_state_api_stories__story_id__setup_get"];
        put?: never;
        /** Submit Setup */
        post: operations["submit_setup_api_stories__story_id__setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["list_personas_api_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BranchCountRange
         * @description Validated branch-count ranges by interaction style.
         *
         *     Hybrid allows: 1-2, 2-3, 3-4.
         *     True CYOA allows: 2-3, 2-4, 2-5.
         * @enum {string}
         */
        BranchCountRange: "1-2" | "2-3" | "3-4" | "2-4" | "2-5";
        /**
         * BranchOption
         * @description Branch option with code-assigned identity, ready for delivery.
         *
         *     ``option_id`` is assigned by code (sequential ``opt_1``, ``opt_2``, …).
         *     ``action_text`` comes from the model proposal after range validation.
         */
        BranchOption: {
            /** Option Id */
            option_id: string;
            /** Action Text */
            action_text: string;
        };
        /**
         * BranchPresentationState
         * @description Whether branch-choice cards are shown, held, or omitted for a beat.
         *
         *     SHOWN: branch cards are rendered for the Sojourner this beat.
         *     HELD: branch cards exist but are withheld (e.g. mid-scene tension).
         *     OMITTED: no branch cards for this beat (freeform or narrative-only).
         * @enum {string}
         */
        BranchPresentationState: "shown" | "held" | "omitted";
        /**
         * BranchingCadence
         * @description Branching-mode pacing density — distinct axis from PacingStage.
         * @enum {string}
         */
        BranchingCadence: "interactive" | "balanced" | "immersive";
        /**
         * BranchingSetupRequest
         * @description Branching structured setup fields. The confirmation pass itself is an
         *     ordinary DELIVERED turn (ADR-016 Decision 3) -- submit it via
         *     POST .../turns after this call, not through this route.
         */
        BranchingSetupRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "branching";
            interaction_style?: components["schemas"]["InteractionStyle"] | null;
            branching_cadence?: components["schemas"]["BranchingCadence"] | null;
            branch_count_range?: components["schemas"]["BranchCountRange"] | null;
            length_preference?: components["schemas"]["LengthPreference"] | null;
            /**
             * Clear Branch Count Range
             * @default false
             */
            clear_branch_count_range: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * BranchingSetupStateDTO
         * @description Currently-persisted Branching setup/config fields. Branching already
         *     bypasses SetupForm on reload once persisted visible state exists
         *     (StoryView's ``structuredSetupPersisted``), so no frontend hydration
         *     consumes this today -- included for GET .../setup symmetry across modes.
         */
        BranchingSetupStateDTO: {
            /**
             * Mode
             * @constant
             */
            mode: "branching";
            interaction_style?: components["schemas"]["InteractionStyle"] | null;
            branching_cadence?: components["schemas"]["BranchingCadence"] | null;
            branch_count_range?: components["schemas"]["BranchCountRange"] | null;
            length_preference?: components["schemas"]["LengthPreference"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * BranchingVisibleState
         * @description Structured branching session state surfaced in OrchestrationResult.
         *
         *     Populated by ``BranchingVisibleStateService`` on every DELIVERED
         *     BRANCHING-mode turn.  Carries the current config and the most-recently-
         *     presented branch options so the frontend can render the branch card.
         *
         *     ``schema_version`` allows forward-compatible reads by callers.
         */
        BranchingVisibleState: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            interaction_style: components["schemas"]["InteractionStyle"];
            branching_cadence: components["schemas"]["BranchingCadence"];
            branch_count_range: components["schemas"]["BranchCountRange"] | null;
            /** Freeform Available */
            freeform_available: boolean;
            length_preference: components["schemas"]["LengthPreference"] | null;
            /** Last Branch Options */
            last_branch_options?: components["schemas"]["BranchOption"][] | null;
            last_presentation_state?: components["schemas"]["BranchPresentationState"] | null;
        };
        /** CreateStoryRequest */
        CreateStoryRequest: {
            /** Title */
            title: string;
            mode: components["schemas"]["StoryMode"];
            /** Character Name */
            character_name?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * CritiqueIntensity
         * @description How directly the persona delivers feedback.
         * @enum {string}
         */
        CritiqueIntensity: "gentle" | "balanced" | "blunt" | "ruthless";
        /**
         * DiceHandling
         * @description Dice-roll mode configured by the player in RPG mode.
         * @enum {string}
         */
        DiceHandling: "player_rolls" | "ai_rolls";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Db Reachable */
            db_reachable: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * IntentType
         * @description Classified intent of a user input or story beat.
         *
         *     The full eight-type taxonomy is defined in Issue 7 (CRD Issue 7).
         *     ``Node.intent_type`` uses this same enum but logically draws from the
         *     narrower five-type subset (IN_CHARACTER_ACTION, DIALOGUE,
         *     AUTHOR_INSTRUCTION, BRANCH_CHOICE, BEAT_MILESTONE) that describes what a
         *     Node *represents* in the story graph.  ``Turn.intent_classification`` uses
         *     the full taxonomy, including REWIND, LORE_QUESTION, and OOC.
         * @enum {string}
         */
        IntentType: "in_character_action" | "dialogue" | "author_instruction" | "branch_choice" | "beat_milestone" | "rewind" | "lore_question" | "ooc";
        /**
         * InteractionRejectionReason
         * @description Typed reason an Interaction was rejected (CRD Issue 16).
         *
         *     Used in ``OrchestrationResult.interaction_rejection_reason`` when
         *     ``disposition`` is ``INTERACTION_REJECTED``.  A human-readable message
         *     is always emitted alongside this typed reason via
         *     ``interaction_rejection_message``.
         *
         *     INVALID_FOR_INTERACTION_STYLE: input style is incompatible with the
         *         current ``InteractionStyle`` (e.g. freeform prose in TRUE_CYOA).
         *     MATERIAL_BRANCH_REWRITE: a branch annotation materially rewrites the
         *         label in a way that changes the canonical meaning.
         *     CANON_OR_GENRE_CONTRADICTION: the selected action violates Story Bible
         *         canon or established genre constraints.
         *     INVALID_BRANCH_SELECTION: BRANCH_CHOICE intent references an option_id
         *         that does not appear in the most-recently-presented branch card set.
         * @enum {string}
         */
        InteractionRejectionReason: "invalid_for_interaction_style" | "material_branch_rewrite" | "canon_or_genre_contradiction" | "invalid_branch_selection";
        /**
         * InteractionStyle
         * @description Branching-mode interaction contract: how the Sojourner interacts.
         * @enum {string}
         */
        InteractionStyle: "freeform_only" | "hybrid" | "true_cyoa";
        /**
         * LengthPreference
         * @description Preferred response length for Branching-mode narrative beats.
         * @enum {string}
         */
        LengthPreference: "short_story" | "novella" | "novel";
        /** PersonaDTO */
        PersonaDTO: {
            /** Persona Id */
            persona_id: string;
            /** Display Name */
            display_name: string;
            /** Orientation */
            orientation: string;
            /** Ui Short Description */
            ui_short_description: string;
            /** Ui Long Description */
            ui_long_description: string;
            /** Demeanor Tags */
            demeanor_tags: string[];
            /** Signature Move */
            signature_move: string;
        };
        /** PersonaGalleryResponse */
        PersonaGalleryResponse: {
            /** Mentors */
            mentors: components["schemas"]["PersonaDTO"][];
            /** Peers */
            peers: components["schemas"]["PersonaDTO"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * PersonaOrientation
         * @description Mentor personas teach through making; Peer personas collaborate alongside.
         * @enum {string}
         */
        PersonaOrientation: "mentor" | "peer";
        /**
         * PipelineDisposition
         * @description Exhaustive terminal states of a Sojourn Turn (Issue 12c).
         *
         *     Adding a new disposition is a load-bearing change: it requires a new
         *     value here, a new entry in the result-population invariant validator on
         *     ``OrchestrationResult``, and a corresponding test in the disposition
         *     matrix.  See Issue 12c "Architectural Invariants to Enforce" #7.
         * @enum {string}
         */
        PipelineDisposition: "delivered" | "ooc_handled" | "blocked_input_safety" | "blocked_output_safety" | "blocked_contradiction" | "blocked_pending_roll" | "interaction_rejected" | "refused_by_provider" | "pipeline_error";
        /**
         * ProviderRefusalSummaryDTO
         * @description Advisory only -- never authoritative policy (mirrors ProviderRefusal).
         *
         *     Deliberately excludes ``raw_response_excerpt``, ``pass_identifier``, and
         *     ``refusal_category``: internal routing/audit detail, not a client
         *     contract (Binding Decision 9).
         */
        ProviderRefusalSummaryDTO: {
            /** Provider */
            provider: string;
            /** Coarse Reason */
            coarse_reason?: string | null;
        };
        /**
         * RpgSessionType
         * @description Pacing expectation set by the Sojourner at play configuration.
         * @enum {string}
         */
        RpgSessionType: "short_adventure" | "campaign" | "open_ended";
        /**
         * RpgSetupRequest
         * @description RPG play-config form fields. Conversational setup (character creation,
         *     world-building) goes through ordinary turn submission, not this route --
         *     Issue 15's own pipeline owns setup_phase/play_status progression.
         */
        RpgSetupRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "rpg";
            dice_handling?: components["schemas"]["DiceHandling"] | null;
            /** Gm Cheating */
            gm_cheating?: boolean | null;
            tone?: components["schemas"]["RpgTone"] | null;
            session_type?: components["schemas"]["RpgSessionType"] | null;
            /** Genre Flavor */
            genre_flavor?: string | null;
            /** House Rules */
            house_rules?: string | null;
            /** Acceptable Content */
            acceptable_content?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * RpgSetupStateDTO
         * @description Currently-persisted RPG setup/config fields (PR #126 review round 5,
         *     P2). Unlike ``RpgSetupRequest``, every field is optional -- this reflects
         *     whatever has been saved so far, which may be partial or (for a brand-new
         *     story) all-default. Read-only mirror of ``RpgSetupRequest``'s field set;
         *     not a general character-sheet or setup-progress surface.
         */
        RpgSetupStateDTO: {
            /**
             * Mode
             * @constant
             */
            mode: "rpg";
            dice_handling?: components["schemas"]["DiceHandling"] | null;
            /** Gm Cheating */
            gm_cheating?: boolean | null;
            tone?: components["schemas"]["RpgTone"] | null;
            session_type?: components["schemas"]["RpgSessionType"] | null;
            /** Genre Flavor */
            genre_flavor?: string | null;
            /** House Rules */
            house_rules?: string | null;
            /** Acceptable Content */
            acceptable_content?: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * RpgTone
         * @description Consequence severity calibration configured at play configuration.
         * @enum {string}
         */
        RpgTone: "gritty" | "balanced" | "forgiving" | "danger_free";
        /**
         * RpgVisibleState
         * @description Visible game state for the RPG mode sidebar / visible-state surface.
         *
         *     Character-visible only.  Hidden state (hidden rolls, unseen threats,
         *     undetected NPCs, hidden relationships) excluded by construction.
         *     ``schema_version`` is a payload version lock — consumers must check it.
         */
        RpgVisibleState: {
            character: components["schemas"]["VisibleCharacterState"];
            /** Inventory */
            inventory: components["schemas"]["VisibleItem"][];
            location?: components["schemas"]["VisibleLocation"] | null;
            /** Relationship Meters */
            relationship_meters: components["schemas"]["VisibleRelationship"][];
            /** Known Objectives */
            known_objectives: string[];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** SetupResponse */
        SetupResponse: {
            /** Visible State */
            visible_state?: components["schemas"]["RpgVisibleState"] | components["schemas"]["BranchingVisibleState"] | components["schemas"]["WritingVisibleState"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * SetupStateResponse
         * @description Response for ``GET /api/stories/{story_id}/setup`` (PR #126 review
         *     round 5, P2): lets a setup form hydrate its initial state from what is
         *     already persisted, instead of always starting from hardcoded defaults
         *     and silently overwriting a prior save on the next submit.
         */
        SetupStateResponse: {
            /** Setup State */
            setup_state?: components["schemas"]["RpgSetupStateDTO"] | components["schemas"]["BranchingSetupStateDTO"] | components["schemas"]["WritingSetupStateDTO"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StoryDetailDTO */
        StoryDetailDTO: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            mode: components["schemas"]["StoryMode"];
            status: components["schemas"]["StoryPlayStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StoryListItemDTO */
        StoryListItemDTO: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            mode: components["schemas"]["StoryMode"];
            status: components["schemas"]["StoryPlayStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** StoryListResponse */
        StoryListResponse: {
            /** Stories */
            stories: components["schemas"]["StoryListItemDTO"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * StoryMode
         * @description The three narrative modes of Afterworlds.
         * @enum {string}
         */
        StoryMode: "rpg" | "branching" | "writing";
        /**
         * StoryPlayStatus
         * @description API-facing setup/play status, shared shape across all three modes.
         * @enum {string}
         */
        StoryPlayStatus: "setup" | "in_play";
        /**
         * StyleDensity
         * @description Prose density preference for the writing project.
         * @enum {string}
         */
        StyleDensity: "sparse" | "balanced" | "lush" | "literary" | "pulp";
        /** TranscriptResponse */
        TranscriptResponse: {
            /** Turns */
            turns: components["schemas"]["TranscriptTurnDTO"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** TranscriptTurnDTO */
        TranscriptTurnDTO: {
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            /** User Input */
            user_input: string;
            /** Assistant Output */
            assistant_output: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            intent_classification: components["schemas"]["IntentType"];
        };
        /** TurnSubmissionRequest */
        TurnSubmissionRequest: {
            /** User Input */
            user_input: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * TurnSubmissionResponse
         * @description The turn-submission envelope (Binding Decisions 3, 6, 10, 11).
         */
        TurnSubmissionResponse: {
            disposition: components["schemas"]["PipelineDisposition"];
            /** Turn Id */
            turn_id: string | null;
            /** Delivered Output */
            delivered_output?: string | null;
            /**
             * Stable Prefix Cache Warmed
             * @default false
             */
            stable_prefix_cache_warmed: boolean;
            interaction_rejection_reason?: components["schemas"]["InteractionRejectionReason"] | null;
            /** Interaction Rejection Message */
            interaction_rejection_message?: string | null;
            /** Pipeline Error Summary */
            pipeline_error_summary?: string | null;
            provider_refusal?: components["schemas"]["ProviderRefusalSummaryDTO"] | null;
            /** Pending Roll Redirect Message */
            pending_roll_redirect_message?: string | null;
            /** Settlement Warning */
            settlement_warning?: string | null;
            /** Visible State */
            visible_state?: components["schemas"]["RpgVisibleState"] | components["schemas"]["BranchingVisibleState"] | components["schemas"]["WritingVisibleState"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisibleCharacterState
         * @description Character state visible to the Sojourner.
         *
         *     ``active_conditions`` contains only ``display_label`` strings for
         *     conditions with ``ConditionVisibility.VISIBLE``.  Hidden conditions are
         *     excluded by construction.
         */
        VisibleCharacterState: {
            /** Character Name */
            character_name: string;
            /** Character Class */
            character_class: string;
            /** Level */
            level: number;
            /** Current Hp */
            current_hp: number;
            /** Maximum Hp */
            maximum_hp: number;
            /** Active Conditions */
            active_conditions: string[];
        };
        /**
         * VisibleItem
         * @description An inventory item visible to the Sojourner.
         */
        VisibleItem: {
            /** Name */
            name: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * VisibleLocation
         * @description The current location as the character perceives it.
         */
        VisibleLocation: {
            /** Name */
            name: string;
            /** Brief Description */
            brief_description?: string | null;
        };
        /**
         * VisibleRelationship
         * @description A relationship the character is aware of.
         */
        VisibleRelationship: {
            /** Character Name */
            character_name: string;
            /** Relationship Description */
            relationship_description: string;
        };
        /** VisibleStateResponse */
        VisibleStateResponse: {
            /** Visible State */
            visible_state?: components["schemas"]["RpgVisibleState"] | components["schemas"]["BranchingVisibleState"] | components["schemas"]["WritingVisibleState"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * WritingForm
         * @description Primary form of the writing project.
         * @enum {string}
         */
        WritingForm: "short_story" | "novel" | "narrative_nonfiction" | "memoir" | "screenplay" | "other";
        /**
         * WritingSetupRequest
         * @description Writing setup fields. ``persona_id`` is required -- no default persona.
         *
         *     ``dialogue_narration_ratio`` and ``beat_constraints`` are validated here
         *     to match ``WritingSessionState``'s own validators (P2 remediation, PR
         *     #126 review round 4): ``apply_writing_config_update`` assumes its caller
         *     already validated these -- true for its one production caller
         *     (``WritingConfigUpdate``, the OOC extractor's DTO), but this route calls
         *     it directly with unvalidated client input. Without this, an out-of-range
         *     ratio or a blank beat constraint would flush to the row, then the
         *     immediately-following ``build_visible_state`` re-read would raise while
         *     reconstructing ``WritingSessionState``, turning a client validation
         *     problem into an internal 500 instead of a typed 422.
         */
        WritingSetupRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "writing";
            /** Persona Id */
            persona_id: string;
            /** Specific Goals */
            specific_goals: string;
            critique_intensity?: components["schemas"]["CritiqueIntensity"] | null;
            form?: components["schemas"]["WritingForm"] | null;
            /** Form Other */
            form_other?: string | null;
            /** Tense */
            tense?: string | null;
            /** Pov */
            pov?: string | null;
            style_density?: components["schemas"]["StyleDensity"] | null;
            /** Dialogue Narration Ratio */
            dialogue_narration_ratio?: number | null;
            /** Genre Conventions */
            genre_conventions?: string | null;
            /** Acceptable Content */
            acceptable_content?: string | null;
            /** Beat Constraints */
            beat_constraints?: string[] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * WritingSetupStateDTO
         * @description Currently-persisted Writing setup/config fields. Writing already
         *     bypasses SetupForm on reload once persisted visible state exists
         *     (StoryView's ``structuredSetupPersisted``), so no frontend hydration
         *     consumes this today -- included for GET .../setup symmetry across modes.
         *     Unlike ``WritingSetupRequest``, ``persona_id``/``specific_goals`` are
         *     optional here since setup may not have completed yet.
         */
        WritingSetupStateDTO: {
            /**
             * Mode
             * @constant
             */
            mode: "writing";
            /** Persona Id */
            persona_id?: string | null;
            critique_intensity?: components["schemas"]["CritiqueIntensity"] | null;
            form?: components["schemas"]["WritingForm"] | null;
            /** Form Other */
            form_other?: string | null;
            /** Tense */
            tense?: string | null;
            /** Pov */
            pov?: string | null;
            style_density?: components["schemas"]["StyleDensity"] | null;
            /** Dialogue Narration Ratio */
            dialogue_narration_ratio?: number | null;
            /** Genre Conventions */
            genre_conventions?: string | null;
            /** Specific Goals */
            specific_goals?: string | null;
            /** Acceptable Content */
            acceptable_content?: string | null;
            /** Beat Constraints */
            beat_constraints?: string[] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * WritingVersionPointer
         * @description Lightweight provenance reference to a writing artifact.
         *
         *     A signpost — not a time machine. No parent pointer, diff payload, snapshot
         *     payload, branch ID, restore target, or is_current semantics.
         */
        WritingVersionPointer: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Pointer Id
             * Format: uuid
             */
            pointer_id?: string;
            kind: components["schemas"]["WritingVersionPointerKind"];
            /** Label */
            label: string;
            /** Source Turn Id */
            source_turn_id?: string | null;
            /** Source Node Id */
            source_node_id?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * WritingVersionPointerKind
         * @description What kind of provenance reference a WritingVersionPointer stores.
         * @enum {string}
         */
        WritingVersionPointerKind: "turn" | "node" | "draft_label" | "generated_candidate" | "working_segment";
        /**
         * WritingVisibleState
         * @description Backend DTO for Writing-mode state consumed by Issue 19's HTTP layer.
         *
         *     Registry UI metadata (description, signature move, demeanor) is resolved
         *     from persona_id at assembly time; it is not stored in session state.
         */
        WritingVisibleState: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Persona Id */
            persona_id: string;
            /** Persona Display Name */
            persona_display_name: string;
            relationship_orientation: components["schemas"]["PersonaOrientation"];
            /** Ui Short Description */
            ui_short_description: string;
            /** Ui Long Description */
            ui_long_description: string;
            /** Signature Move */
            signature_move: string;
            /** Demeanor Tags */
            demeanor_tags: string[];
            /** Play Status */
            play_status: string;
            /** Specific Goals */
            specific_goals: string;
            /** Reading Interests */
            reading_interests?: string | null;
            /** Writing Interests */
            writing_interests?: string | null;
            critique_intensity: components["schemas"]["CritiqueIntensity"];
            form: components["schemas"]["WritingForm"] | null;
            /** Form Other */
            form_other?: string | null;
            /** Tense */
            tense: string | null;
            /** Pov */
            pov: string | null;
            style_density: components["schemas"]["StyleDensity"];
            /** Dialogue Narration Ratio */
            dialogue_narration_ratio: number | null;
            /** Genre Conventions */
            genre_conventions: string | null;
            /** Beat Constraints */
            beat_constraints: string[];
            /** Version Pointers */
            version_pointers: components["schemas"]["WritingVersionPointer"][];
            /** Acceptable Content */
            acceptable_content: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_stories_api_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryListResponse"];
                };
            };
        };
    };
    create_story_route_api_stories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_route_api_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_stories__story_id__turns_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_api_stories__story_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visible_state_api_stories__story_id__visible_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisibleStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setup_state_api_stories__story_id__setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_setup_api_stories__story_id__setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpgSetupRequest"] | components["schemas"]["BranchingSetupRequest"] | components["schemas"]["WritingSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_api_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaGalleryResponse"];
                };
            };
        };
    };
}
