"""Regenerate the committed expected-table inventory — CRD Issue 5c, PR #134 R15 F4.

Deterministic offline procedure that produces the frozen oracle
(``srd_table_inventory.json``) the table concordance checks against. Run this only
after an intentional, reviewed table-reconstruction change; the committed file is
then the reviewed expectation, and its hash re-mints the release identity.

    python scripts/regen_table_inventory.py
"""

from __future__ import annotations

import json
from pathlib import Path

from afterworlds.ingestion.corpus.pdf_source import extract_pages
from afterworlds.ingestion.corpus.table_inventory import (
    build_table_inventory,
    inventory_hash,
    source_inventory_path,
)

_PDF = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "sources"
    / ("DnD5_5e_SRD_CC_v5_2_1.pdf")
)


def main() -> None:
    inventory = build_table_inventory(extract_pages(_PDF))
    payload = {
        "_comment": (
            "Frozen expected-table oracle for the SRD 5.2.1 corpus. Generated by "
            "scripts/regen_table_inventory.py from the committed PDF + frozen "
            "detection code; do not hand-edit. See table_inventory.py for the "
            "provenance/regeneration contract. The table concordance compares the "
            "live reconstruction against this file so suppressed/flattened/"
            "fragmented/merged/invented tables fail."
        ),
        "inventory_hash": inventory_hash(inventory),
        "table_count": len(inventory),
        "tables": inventory,
    }
    out_path = source_inventory_path()
    out_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(
        f"wrote {len(inventory)} tables to {out_path} "
        f"(hash {payload['inventory_hash']})"
    )


if __name__ == "__main__":
    main()
